let a=42;
console.log( a, "->" , typeof a);
let b="Bonjour";
console.log( b, "->" + typeof b);
let c=true;
console.log( c ,"->" + typeof c);
let d=null;
console.log(d ,"-> " + typeof d);
let e=undefined;
console.log( e, "-> " + typeof e);
let f = [1, 2, 3];
console.log( f ,"->" + typeof f);
let g = { nom: "Ali" };
console.log(g, "->" + typeof g);
let h = NaN;
console.log(h,"->" + typeof h);